/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#aa96da",
          foreground: "#ffffff",
          50: "#f8f6ff",
          100: "#f0ebff",
          200: "#e3d9ff",
          300: "#d1bfff",
          400: "#bb9eff",
          500: "#aa96da",
          600: "#9b7dd4",
          700: "#8b70cd",
          800: "#7a5fc4",
          900: "#6b4fb8",
        },
        accent: {
          DEFAULT: "#8b70cd",
          foreground: "#ffffff",
          50: "#f5f2ff",
          100: "#ebe5ff",
          200: "#d9ccff",
          300: "#c4a8ff",
          400: "#ab7aff",
          500: "#8b70cd",
          600: "#7c5bc4",
          700: "#6d47bb",
          800: "#5e33b2",
          900: "#4f1fa9",
        },
        neutral: {
          DEFAULT: "#e6e6e6",
          50: "#fafafa",
          100: "#f5f5f5",
          200: "#e6e6e6",
          300: "#d4d4d4",
          400: "#a3a3a3",
          500: "#737373",
          600: "#525252",
          700: "#404040",
          800: "#262626",
          900: "#171717",
        },
        secondary: {
          DEFAULT: "#c9bce7",
          foreground: "#1f2937",
          50: "#faf9ff",
          100: "#f4f1ff",
          200: "#ebe5ff",
          300: "#ddd2ff",
          400: "#c9bce7",
          500: "#b5a3d9",
          600: "#a18acb",
          700: "#8d71bd",
          800: "#7958af",
          900: "#653fa1",
        },
        soft: {
          DEFAULT: "#e7e1f5",
          50: "#fdfcff",
          100: "#faf8ff",
          200: "#f5f1ff",
          300: "#ede5ff",
          400: "#e7e1f5",
          500: "#d9cce7",
          600: "#cbb7d9",
          700: "#bda2cb",
          800: "#af8dbd",
          900: "#a178af",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "fade-out": {
          from: { opacity: "1" },
          to: { opacity: "0" },
        },
        "slide-in-from-top": {
          from: { transform: "translateY(-100%)" },
          to: { transform: "translateY(0)" },
        },
        "slide-in-from-bottom": {
          from: { transform: "translateY(100%)" },
          to: { transform: "translateY(0)" },
        },
        "slide-in-from-left": {
          from: { transform: "translateX(-100%)" },
          to: { transform: "translateX(0)" },
        },
        "slide-in-from-right": {
          from: { transform: "translateX(100%)" },
          to: { transform: "translateX(0)" },
        },
        "scale-in": {
          from: { transform: "scale(0.95)", opacity: "0" },
          to: { transform: "scale(1)", opacity: "1" },
        },
        "scale-out": {
          from: { transform: "scale(1)", opacity: "1" },
          to: { transform: "scale(0.95)", opacity: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.2s ease-out",
        "fade-out": "fade-out 0.2s ease-out",
        "slide-in-from-top": "slide-in-from-top 0.3s ease-out",
        "slide-in-from-bottom": "slide-in-from-bottom 0.3s ease-out",
        "slide-in-from-left": "slide-in-from-left 0.3s ease-out",
        "slide-in-from-right": "slide-in-from-right 0.3s ease-out",
        "scale-in": "scale-in 0.2s ease-out",
        "scale-out": "scale-out 0.2s ease-out",
      },
      boxShadow: {
        'soft': '0 2px 15px -3px rgba(0, 0, 0, 0.07), 0 10px 20px -2px rgba(0, 0, 0, 0.04)',
        'soft-lg': '0 10px 40px -15px rgba(0, 0, 0, 0.1), 0 20px 25px -5px rgba(0, 0, 0, 0.04)',
        'glow': '0 0 20px rgba(170, 150, 218, 0.3)',
        'glow-accent': '0 0 20px rgba(139, 112, 205, 0.4)',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}